### ISSUE TITLE
Command line interface consume mode error

### ISSUE THREAD

**Issue by ccjiang168** [ckan/ckanext-dcat#131]
Hi,

I tried the command line interface in consume mode
" python ckanext/dcat/processors.py consume examples/catalog.rdf -P "
and got the error messages below

==================================================================
Traceback (most recent call last):
  File "ckanext/dcat/processors.py", line 455, in <module>
    ckan_datasets = [d for d in parser.datasets()]
  File "ckanext/dcat/processors.py", line 183, in datasets
    profile.parse_dataset(dataset_dict, dataset_ref)
  File "/usr/lib/ckan/default/src/ckanext-dcat/ckanext/dcat/profiles.py", line 795, in parse_dataset
    dataset_dict['license_id'] = self._license(dataset_ref)
  File "/usr/lib/ckan/default/src/ckanext-dcat/ckanext/dcat/profiles.py", line 333, in _license
    license_title2id[license.title] = license_id
  File "/usr/lib/ckan/default/src/ckan/ckan/model/license.py", line 50, in __getattr__
    return self._data[name]
  File "/usr/lib/ckan/default/src/ckan/ckan/model/license.py", line 201, in __getitem__
    value = getattr(self, key)
  File "/usr/lib/ckan/default/src/ckan/ckan/model/license.py", line 222, in title
    return _("License not specified")
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/i18n/translation.py", line 106, in ugettext
    return pylons.translator.ugettext(value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: translator) has been registered for this thread

==================================================================

Does it relate to the example files ?
Or the issue in DCAT license field then I should write a customized profile ?
Or something else ?

Thanks for any suggestions or a workable example

**Comment by amercader** [comment]
Thanks @ccjiang168. I pushed a workaround to fix this. If you pull the latest master it should work now.
